# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20be1c338aa628d7e5dc09afb6023ce717482722829375b900d13913efd2d029e4775ad5104662276e6fa035a860638685dff284d745d8a49f30b71a6e7c824e

test:
  secret_key_base: 2eb97c7f772083ecd993f57ccc8ab347612671d1749b184e6833f497dd0f64a7b9cb048455d6be13d5f8aa96ddb21020ac0e86530373d91b67f32ac97942b485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
